### PR TITLE
Updated judge uml

### PR DESCRIPTION
**Pull request by candicez03**
Issue:
- SourceExecutor returns a started Process only, which does not allow the same program to be reran for multiple testcases
- there is no appropiate class to handle temporary program file generation and cleanup(after submission is tested)

Fix:
- SourceExecutor  will act as a ProcessBuilder only
- Tester will manage the file generation and cleanup, as a Callable, and return an array of testcase runs
- upon testing, Tester will start the same SourceExecutor multiple times with different testcases

### CODE REVIEW

**Review by beepboop271 — CHANGES_REQUESTED** [review]
image
What does `ProgramExecutor` do now? It looks to me like you're doing
```text
Judger -> ProgramChecker
|      <- |
|
|      -> ProgramExecutor -> Tester -> SourceExecutor
|         |                  |      <- |
|         |               <- |
|      <- |
```
(Diagram not exactly correct for simplicity)
Having `ProgramExecutor` call `Tester`, which is not correct. The checker is supposed to check code, the executor is supposed to launch it (and now changed to prepare the program to be launched quickly with a single `.start()`), and the tester is supposed to test a single case (I realize now that the tester originally had testing the entire problem at once, returning a `TestcaseRun[]`, which is not right (even if you want to test the whole program in tester, you still need to consider batches)).

The connecting logic (e.g. where to pass the `ProcessBuilder`, where to loop to run all the cases in a problem) should be in `Judger`: it uses the three services provided by the checker, executor, and tester. Those services are (or at least should be) completely separated from each other in terms of their implementation since they don't depend on each other. The only dependency is that `Judger` needs all 3 to complete the task of judging a submission.

If a `Tester` only needs to use a `ProcessBuilder` (or just a wrapping class that only exposes `.start()`), why should it create it? If `SourceExecutor` is the only class that needs to deal with actual files, why is `Tester` creating the files? Essentially you have delegated too much work into the `Tester` class (which is just supposed to test), when other classes were made to have that purpose (e.g. if creating files is only needed in the setup part, just create and destroy them in `SourceExecutor`, if passing information between the executor and tester is not specifically about testing, why not put it in `Judger`, which is supposed to perform the judging process as a whole).

The more I look at it the more I realize just how much you have put into `Tester`, it looks like you're compiling files with it as well? I think now that we realise compilation/setup in general and actually running the program are different, it might be a good idea to move the execution thread pool somewhere else, so that `ProgramExecutor` can go back to its updated intended job, maybe rename it too. Putting the thread pool elsewhere (e.g. directly in `Judger`, since it'll be used by both the executor and tester to do completely different things) might help you separate everything.

`Judger`:
- Receives a `Submission`
- Calls `ProgramChecker` for a true/false on if the source is okay to run
- Calls `ProgramExecutor` to get a `SourceExecutor` (perhaps pass it the thread pool executor so that you're not returning `Callable<SourceExecutor>`, which is kind of strange), which involves creating necessary files and compiling if needed
- Calls `Tester` repeatedly with the newly produced `SourceExecutor` (again, maybe pass it the thread pool), which returns one `TestcaseRun` for each test and involves starting the program
- Produces an overall result for the whole submission, based on the runs it received from the tester
- Calls some cleanup method on the `SourceExecutor` to delete temporary files

Also, why are you extending `ProcessBuilder`? Doesn't that expose all the public methods of `ProcessBuilder` onto a `SourceExecutor` object, which allows someone to modify the command that is being run?

Note: you may need to add some small inner classes that implement `Callable` to do this?

**Comment by candicez03** [comment]
- `Tester` now is only responsible for testing a single testcase at a time
- `ProgramExecutor` is renamed to `SourceExecutorService`, since it only has a method for getting a `SourceExecutor` (I hope this is not too sketchy)
- Added inner Callable classes to `SourceExecutorService` and `Tester`
- The thread pool is moved into `Judger`, which will be used by both `SourceExecutorService` and `Tester`
- `SourceExecutor` no longer extends `ProcessBuilder`; methods are added for temp file creation and deletion

**Review by beepboop271 — CHANGES_REQUESTED** [review]
`SourceExecutor`:
- Consider implementing `AutoCloseable`
- `- abstract File createTempFile()` Is this really `abstract`? All languages will be submitted in a single file which needs to go in a single directory
- `- abstract List<String> getCommands()` Is this really a good or even possible way to implement it? You need to have two language dependent things - the setup process (e.g. `javac` command) and the execution process (e.g. `java` command), so there should probably be more than just "get commands"
- `JavaExecutor`, `PythonExecutor`, and `SourceExecutor` are more of a setup and process launching thing, which makes executor a bit of a strange name

> `ExecutorService threadPool`

An `ExecutorService` is not necessarily a thread pool, consider a different name.

> `+ static TestcaseRun test(...)`

Consider returning a future instead: returning a `TestcaseRun` means you get/join on the future inside the `Tester` code ie. you wait inside `Tester` until it is done with a single test case. This means the caller (`Judger`) would have to wait for every test to finish before even being able to launch the next one.

By returning a future, the `Judger` can loop over all the tests to run, with each test returning immediately, and use something like `CompletableFuture.allOf` to wait for all the returned futures to complete. This is better because the executor has its own job queue, sometimes it will be able to run 10 tests from `Judger` at once, sometimes it will be able to do just 1, but by enqueuing all jobs at once and waiting for them to eventually complete, there will be as little wasted time as possible. Note you will need to use your own `CompletableFuture`, not the default `Future` returned by the executor, since you can't really do much with normal futures.

You could also change source executor to use futures too (just to be more consistent), even though we'll need to wait for that to complete before anything else can be done.

**Comment by candicez03** [comment]
Renamed classes that have executor in their names:
- `SourceExecutorService` → `SourceLauncherService`
- `SourceExecutorGetter` → `SourceLauncherGetter`
- `SourceExecutor`  → `SourceLauncher`
- `JavaExecutor` → `JavaLauncher`
- `PythonExecutor` → `PythonLauncher`


`SourceLauncher`:
- Now implements `AutoCloseable` for closing the resources (temp files, etc.)
- Made createTempFile() non-abstract, separated the language-dependent suffix getter to `getTempFileExtension()`
- Separated the setup and launching methods. `setup()` calls relavent methods to create temp files, etc.; child classes can override and do extra preparation(e.g. compilation of a file) if necessary. `launch()` simply launches the program and returns a Process representing it.


`Tester.test(...)` and `SourceLauncherService.getSourceLauncher(...)` now both return a `CompletableFuture`.

**Review by beepboop271 — APPROVED** [review]

**Pull request merged**
